### ISSUE TITLE
Why were we kicked out of the 2.0 release?

### ISSUE THREAD

**Issue by robertostling** [UniversalDependencies/UD_Swedish_Sign_Language-SSLC#1]
@fginter @dan-zeman 

I might have missed something, but did criteria for inclusion change between version 1.4 and 2.0 of the UD treebanks? I noticed this one was dropped in v2.0.

I'm not arguing with the decision, we're well aware that the data we submitted for v1.4 was very small and the POS annotations in particular had issues. But now we are back to annotating new data and revising the old files, so we would like to know what is necessary to get into the 2.1 release (in terms of data size, quality, etc.)

Another question is if we should add the testset again, which was removed from the repo ahead of the CoNLL shared task?

**Comment by jnivre** [comment]
The criteria were not changed. The only reason this treebank was not included in v2.0 was that it hadn't been converted to v2 of the guidelines. So the only thing that is needed for inclusion in v2.1 is compliance with v2 (= passing validation). And I believe the test set should be added back (unless Dan and Filip has other ideas about this).

**Comment by robertostling** [comment]
Thanks!

**Comment by dan-zeman** [comment]
Yes, please add the test data back. (I did this automatically for the languages that were in the shared task but since SSL was not there, this test set slipped out.
